### ISSUE TITLE
Is there a way to view the XML being sent to the web server?

### ISSUE THREAD

**Issue by omaralqady** [warseph/soap-as-promised#10]
I want to see the XML that is being sent to the server, but I want to see it on my local machine before it is sent, is there a way to do this?

I've looked through the docs for this lib and for https://www.npmjs.com/package/soap, but I can't find anything about this, so any help would be appreciated.

**Comment by warseph** [comment]
Hi @omaralqady, using soap-as-promised you can see the XML after it was sent, using `client.lastRequest`.

I don't think you can just generate it without sending it, but I know that if you create a Security object for node-soap it can see the generated XML before it's sent (and even edit it). 
Please check their documentation, or you can talk to the node-soap developers in https://gitter.im/vpulim/node-soap.

As this isn't an actual issue with this library I'll close it. Good luck!

**Comment by omaralqady** [comment]
Thank you for your help. I couldn't find this anywhere :)
