### ISSUE TITLE
Soap Using Callbacks instead of Promise

### ISSUE THREAD

**Issue by pljeskavica** [warseph/soap-as-promised#14]
Using the library on an endpoint with BasicAuthSecurity causes issues with the library resolving to the next .then.  
This is how I expect to use the library:
```
export default function soapPromise(url, soapMethod, soapParams){
  return new Promise( (resolve, reject) => {
    soap.createClient(url)
      .then( client => {
        client.setSecurity( new soap.BasicAuthSecurity(username, password));
        client[soapMethod](soapParams)
      .then((result) => { resolve(result) })
      .catch((error) => {reject(error)})
  });
}
```
After creating the soap client, I set the security as done in parent library and as talked about in a previous issue.  Then everything else should operate as if there was no security, call the method and handle the result in the next .then.

Unfortunately while this passes the http auth security issue it will not pass on the result to the next .then as it would if we were accessing a soap endpoint that does not have auth.  (I use this function to access multiple soap endpoints.)

The following is the only way I can get this to work:
```
export default function soapPromise(url, soapMethod, soapParams){
  return new Promise( (resolve, reject) => {
    soap.createClient(url)
      .then( client => {
        client.setSecurity( new soap.BasicAuthSecurity(username, password));
        client[soapMethod](soapParams, (err, res) => {
          if(err){reject(err)}
          resolve(res);
        });
      })
      .then((result) => {
      })
      .catch((error) => {reject(error)})
  });
}
```
As you can see, I have to access the result through a callback, which is of course not the desired outcome.  I also have to remove any resolve call in the second .then function because it resolves immediately, before the result actually comes back from the soap method. 

Just to save time, here is the similar function using the parent library which works perfectly:
```
const method = "ValidateUser";
const ValidateUser = (validateUserPackage) =>{
  soap.createClient(wageringURL, (err, client) => {
    client.setSecurity(new soap.BasicAuthSecurity(user, password));
    if(err){return console.log(err)}

    client[method](validateUserPackage, (err, result, raw, soapHeader) => {
      if(err){
        console.log(`Error: \n${err}`);
      }
      console.log(result);
    });
  }); 
}
```

If Im using the library wrong please let me know.

**Comment by warseph** [comment]
Hi @pljeskavica!
I'm having a bit of trouble understanding how you want to use the library, so please let me know if I didn't get it correctly.
I think this would be what you want:
```js
export default function soapPromise(url, soapMethod, soapParams) {
  return soap.createClient(url)
    .then(client => {
      client.setSecurity(new soap.BasicAuthSecurity(username, password));
      return client;
    })
    .then(client => client[soapMethod](soapParams));
}
```
Let me know if that works or if you need additional help.

Cheers!

**Comment by warseph** [comment]
Hi @pljeskavica, did it work? Let me know so I can close the issue.

Cheers!

**Comment by warseph** [comment]
Ok, I'm closing this issue, let me know if it wasn't solved.
