### ISSUE TITLE
Set accept-language header on request

### ISSUE THREAD

**Issue by ednx** [warseph/soap-as-promised#15]
Hi,

I am trying to send the language header in the request, but I do not identify where I should put it.

const options = {
    wsdl_options: {
        'auth': {
            'user': USER_NAME,
            'pass': USER_PASS,
            'sendImmediately': false
        },
        'accept-language': 'es'
    }
};

soap.createClient(ROOTE_WSDL, options, (err, client) => {...});

**Comment by warseph** [comment]
Hi @ednx, I think this should work:
```js
const options = {
  wsdl_options: {
    auth: {
      user: USER_NAME,
      pass: USER_PASS,
      sendImmediately: false
    },
    wsdl_headers: {
      'accept-language': 'es'
    }
  }
};
```
However, if you are using callbacks, you are using the `node-soap` library directly, feel free to ask them for support on their gitter chat (https://gitter.im/vpulim/node-soap).

I'm gonna close this as it's not really an issue with this library.
