### ISSUE TITLE
postProcess option on client.MyFunction(params, options) call

### ISSUE THREAD

**Issue by saudraisn** [warseph/soap-as-promised#16]
Hi,
Is there a way to set the postProcess option on a client function call?

I wrote a little example to illustrate : (using this SOAP api : http://www.webservicex.net/WS/WSDetails.aspx?WSID=31&CATID=13)

```javascript
let soap = require('soap-as-promised')

soap
  .createClient('http://www.webservicex.net/ConvertTemperature.asmx?WSDL')
  .then(client =>
    client.ConvertTemp(
      { Temperature: 35, FromUnit: 'degreeCelsius', ToUnit: 'degreeFahrenheit' },
      { postProcess: postProcess } //options parameter
    )
  )
  .then(result => console.log(`The result was: `, result))
  .catch(error => console.error(`There was an error! ${error}`))

function postProcess(xml) {
  console.log('The XML is : ' + xml)
  return xml
}
```

In this example, the postProcess function isn't called. I know i can add a security protocol to do the same thing (edit the xml), but i'd really like to be able to do it on function call.

Thanks in advance!

**Comment by warseph** [comment]
Hi @saudraisn, this lib doesn't add any functionality like that to the original `node-soap`.
If what you need is to postProcess the XML that's going to be sent, i'd recommend looking into the security layer of node-soap (https://github.com/vpulim/node-soap#security), it works fine with this library also.
If you want to postProcess the response, you could implement something like that using the `result. _rawResponse` property.
Hope it helps, cheers!

**Comment by saudraisn** [comment]
Hi @warseph, thanks for the fast reply.

Correct me if i'm wrong, but I think it's a functionality that is already included in the original node-soap.

https://github.com/vpulim/node-soap#clientserviceportmethodargs-callback-options-extraheaders---call-a-method-using-a-specific-service-and-port

We can see : 
![image](https://user-images.githubusercontent.com/6865470/32573244-55f397da-c49b-11e7-9a2c-f221fab0ab59.png)

Thanks!

**Comment by warseph** [comment]
Oh, yes, you are right, I wasn't aware of that, it should work then, I'll try to debug it later, it might be related to the node-soap version.

**Comment by warseph** [comment]
The new version should fix the issue @saudraisn, please let me know if it didn't.

Cheers!
