### ISSUE TITLE
Handle authenticate 401 HTTP Code

### ISSUE THREAD

**Issue by mpadmaraj** [warseph/soap-as-promised#18]
We have a scenario where authenticate call to our server gives us back 401 with no body. node-soap is treating this as successful. We notices that in client.js we are not setting the HTTPCODE.
`  if(response.statusCode !== 200 || !output || !output.$lookupTypes) {
        response.pipe(concatStream({encoding: 'string'}, function (body) {
          self.lastResponse = body;
          self.lastResponseHeaders = response && response.headers;
          self.lastElapsedTime = Date.now() - startTime;
          self.emit('response', body, response, eid);

          return parseSync(body, response);

        }));`
has the http code been left out purposefully in the self object? How do you suggest we proceed where the server gives response code other than 200 for incorrect credentials?

**Comment by warseph** [comment]
Hi @mpadmaraj to be honest, I'm not sure how to deal with that, it's a problem of the [node-soap](https://github.com/vpulim/node-soap) library. I'd recommend talking to them on their [gitter](https://gitter.im/vpulim/node-soap). 
Let me know if you think I'm mistaken and this is related to something of this specific library and I'll reopen the issue and look into it again.
