### ISSUE TITLE
Different behavior than the original callback mechanism in createClient callback

### ISSUE THREAD

**Issue by sloncho** [warseph/soap-as-promised#6]
In the callback ("then") of createClient, I change the endpoint using client.setEndpoint. If I set the endpoint to a "bad" server, the client.SomeSvcMethod fails rightfully so using the normal callback mechanism (i.e. err is returned). Using the as-promised looks like swallows the error, and returns a resolved promise with "undefinded".

The funny thing is, that if I set the endpoint in the createClient options, it fails as it should.

This is a mocha test which demonstrates the problem (only the first test fails):

```javascript
'use strict';
require('should');
describe('Expose bug', () => {
	const soapAP = require('soap-as-promised');
	const soapCB = require('soap');

	const WSDL_URL = 'http://www.webservicex.com/globalweather.asmx?WSDL';
	const BAD_SVC_URL = 'http://nonexisting.example.com/somesvc.asmx';

        // ONLY THIS ONE FAILS

	it('should fail with promises when bad url in "then"', () => {
		return soapAP.createClient(WSDL_URL)
			.then(client => {
				client.setEndpoint(BAD_SVC_URL);
				return client.GetWeather();
			})
			.should.be.rejected();
	});

	it('should fail with promises when bad url in createCLient', () => {
		return soapAP.createClient(WSDL_URL, {endpoint: BAD_SVC_URL})
			.then(client => {
				return client.GetWeather();
			})
			.should.be.rejected();
	});

	it('should fail with callback when bad url', (done) => {
		soapCB.createClient(WSDL_URL, (err, client) => {
			// console.log(client.describe());
			client.setEndpoint(BAD_SVC_URL);
			client.GetWeather((err, res) => {
				err.should.not.be.null();
				done();
			});
		});
	});
});
```

I'm using soap-as-promised@1.15.1 and soap@0.15.0.

**Comment by warseph** [comment]
Thanks! It should work well now, I added a test to verify this issue.
setEndpoint reinitialized the client so I needed to "promisify" it again.
