### ISSUE TITLE
Error on create client

### ISSUE THREAD

**Issue by BruceHem** [warseph/soap-as-promised#8]
I'm getting this Target-Namespace "undefined" already in use by another Schema!, has anyone ran into this issue?

**Comment by warseph** [comment]
Hi @BruceHem could you please check if using the node-soap library directly produces the same issue? I think it might be related to the "parent" library.
Please let me know!

**Comment by BruceHem** [comment]
@warseph yes i did, same error appeared.
after the targer-namespace thing this appeared /node_modules/soap/lib/wsdl.js:500
    this.element = schema.elements[nsName.name];
                         ^

**Comment by warseph** [comment]
Ok, it's an error in their library then, I won't be able to help you, it might be the schema is not valid, though I'm not sure.
You can talk to the node-soap developers in https://gitter.im/vpulim/node-soap
I'll close the issue, good luck!
